 <form method="post" action="index.php">
                
                    <label for="firstName ">Prénom</label>
                    <input type="text" name="firstName " id="firstName " />
                    
                    <label for="lastName ">Nom</label>
                    <input type="text" name="lastName " id="lastName " />
                    
                    <label for="password">password</label>
                    <input type="password" name="password" id="password" />
                    
                    <label for="confirmPassword ">confirmPassword </label>
                    <input type="password " name="confirmPassword " id="confirmPassword " />
                    
                    <label for="email">email</label>
                    <input type="email" name="email" id="email" />
                    
                    <label for="formName">hidden</label>
                    <input type="formName " name="formName" id="formName" />
                   
                    
                    <input type="submit" value="Envoyer"/>
            </form>