 <form method="post" action="index.php">
                
                    <label for="email">login</label>
                    <input type="email" name="email" id="email" />
                    
                    <label for="password">password</label>
                    <input type="password" name="password" id="password" />
                    
                    <label for="formName">hidden</label>
                    <input type="formName " name="formName" id="formName" />
                   
                    
                    <input type="submit" value="Envoyer"/>
            </form>